accumulate_grad_batches: 16
batch_size: 4
dev_limit: null
dev_path: data/dev.jsonl
early_stop_patience: 3
embedding_dim: 150
fusion_output_size: 256
img_dir: data/
language_feature_dim: 300
lr: 5.0e-05
max_epochs: 10
n_gpu: 0
output_path: model-outputs
train_path: data/train.jsonl
vision_feature_dim: 300
